apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: docs
build:
  artifacts:
    - image: docker.blockwell.ai/blockwell-docs
deploy:
  kubectl:
    manifests:
      - kubernetes/deployment.yaml
      - kubernetes/ingress.yaml
      - kubernetes/service.yaml
