---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: docs/wallet
  label: Blockwell Wallet
  create: all
  match: "**/*"
  templates:
  - test
- type: directory
  path: docs/contracts
  label: Contracts
  create: all
  match: "**/*"
  templates:
  - test
- type: document
  path: docs/README.md
  label: Home
- type: directory
  path: docs/tools
  label: Tools
  create: all
  match: "**/*"
upload_dir: docs/.vuepress/public
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: docs/.vuepress/dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
